### PR TITLE
Add meta data fields to APIError to allow inspection

### PR DESCRIPTION
**Pull request by hheimbuerger**
(Foreword: This isn't really a complete PR (although this is what I'm working with right now), but rather a request for comments. I'm happy to change my code and switch to an improved interface.)

I'd like to see the `APIError` get more meta data fields to store what led to and caused the error. Specifically, I'd like to be able to inspect the response returned by the API, both for the status code (which indicates the error type on many RESTful APIs) as well as the actual message body (which might contain details, a good example being Twilio's [error details](https://www.twilio.com/docs/api/errors#debugging-calls-to-the-rest-api)).

Example use:

```
try:
    api.posts()
except APIError as exc:
    if exc.status_code == 401:
        raise Reauthenticate()
    elif exc.status_code == 500:
        response_raw = exc.result['_content_]
        response_obj = json.loads(response_raw)
        raise DataRetrievalFailed(response_obj.message)
```

The current naming of the fields on this PR could certainly be improved. One option would also just to provide access to requests' `Response` class. I could imagine that my current implementation fails to provide access to an important aspect of it. On the other hand, passing the whole `Response` class around might be a bit heavy weight, negatively affect serialization of the exception, etc. On the plus side, it would probably allow you to do something like `response.json()`, to let requests handle the decoding, not having to fall back to a manual `json.loads()`.

### CODE REVIEW

**Comment by bujniewicz** [comment]
To be fair, this is the use case for load_json=False, throw_on_error=False, when you want all the details of the response, even if it fails. Throw on error is supposed to be a catch-all. We can modify it to embed response object as-is (without extracting status code and dict - reasoning same as for args/kwargs), but I'm against putting request args and kwargs in there. You should know what arguments are you calling the method with and use that. Leaking internals of library to consumer-controlled code is not the best idea, since we'd be unable to change what goes into args and kwargs without breaking compatibility.

**Comment by hheimbuerger** [comment]
@bujniewicz But `throw_on_error=False` means I'll use 80s error handling instead of exceptions, which I'm really not too keen on. I agree that `throw_on_error` should be a catch-all, in the sense that it throws an exception as soon as any API error occurs, but I don't see anything wrong with then handling these errors—possibly even on a much higher level and across multiple API calls.

Sure, removing `args` and `kwargs` is okay. The reason it would be useful is that you can then have a global error function, which sends all information about the failed call to logging and then you can e.g. report on which calls fail the most later.
But I can see the argument against, too.

**Comment by bujniewicz** [comment]
I think I have an idea to satisfy both rich logging and potential issues with backwards compatibility.

We could introduce a decorator when assigning the entry-point method to API class in GenericAPICreator that would, catch APIErrors and supplement them with concrete model and method names, as well as args and kwargs originally passed. In that scenario the original exception would contain requests response object (in worst case it would require marshalling for serialization, I think we can live with that), it would be caught in the decorator and then extended with call parameters.

I can implement that over the course of the weekend - unless you want to continue with modifying this PR @hheimbuerger ?

**Comment by hheimbuerger** [comment]
@bujniewicz No, I'm happy with you taking it from here. You seem to have a clear sense where you want to go with this library, I just wanted to throw in this idea/feature request.

The decorator approach actually sounds a little bit overengineered to me. Maybe you should ignore my earlier comments on global logging for now, that might not be a good lead in terms of general architecture.

Honestly, for now I would be happy if it was possible for me to access the HTTP response status code and the (in my case always JSON) response body. That would entirely satisfy my current requirements, everything else can be tweaked later based on real world usage, as opposed to my ideas of what could turn into requirements later.

**Comment by bujniewicz** [comment]
@hheimbuerger Alright, in this case - if global logging isn't a requirement right now - you can modify your PR to include the result object only in APIError and I'll be glad to merge it today, otherwise I can work on it tomorrow.

**Comment by bujniewicz** [comment]
Fixed in 0.4.4, available on PyPI.

**Pull request closed without merging**
